export const RESET_LOGS = 'RESET_LOGS';
export const SET_ACTIVE_LOG = 'SET_ACTIVE_LOG';
export const SET_FILE_FORMAT_TYPE = 'SET_FILE_FORMAT_TYPE';
export const SET_CUSTOM_ROW_HANDLER = 'SET_CUSTOM_ROW_HANDLER';
